[package]

name = "unicode_test"
version = "0.0.1"
authors = [ "Sam Pullara <sam@sampullara.com>" ]

[lib]
crate-type = ["cdylib"]

[dependencies]
criterion = "0.2"
rand = "0.7.3"
rand_os = {version = "0.1.0", features = ["wasm-bindgen"]}
same-file = "1.0.6"
wasm-bindgen = "0.2.78"
